tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'htop'
brew 'imagemagick'
brew 'nmap'
brew 'nvm'
brew 'opencv'
brew 'openssl'
brew 'pyenv-virtualenvwrapper'
brew 'readline'
brew 'unrar'
brew 'youtube-dl'

tap 'michaeldfallen/formula'
brew 'git-radar'
