brew 'coreutils'
brew 'fish'
brew 'htop'
brew 'imagemagick'
brew 'nvm'
brew 'pyenv'
brew 'pyenv-virtualenvwrapper'
brew 'readline'
brew 'starship'
brew 'google-cloud-sdk'
brew 'terraform'

tap 'heroku/brew'
brew 'heroku'
