#!/usr/bin/env bash

sudo -v

SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
# DIR is now pointing to the script dir, BASE_PATH is one level up
BASE_PATH="$(cd "$DIR/.." && pwd)"

source "$DIR/common"

source "$DIR/dotfiles"
source "$DIR/apps"

install_dotfiles
run_installers
install_homebrew_dependencies

success "Done."
