alias rs="styleme/manage.py runserver 0.0.0.0:8000"
alias mt="styleme/manage.py test"
alias mm="styleme/manage.py migrate"
alias mmm="styleme/manage.py makemigrations"
alias tp="styleme/manage.py test --failfast && git push"
alias ms="styleme/manage.py shell_plus --ipython"
alias gr="styleme/manage.py generate_reports"
