alias rs="styleme/manage.py runserver"
alias mt="styleme/manage.py test"
alias mm="styleme/manage.py migrate"
alias mmm="styleme/manage.py makemigrations"
alias tp="styleme/manage.py test --failfast && git push"
alias ms="styleme/manage.py shell"
