#!/usr/bin/env zsh

FISH="$HOME/.config/fish"

# If it's not a symlink, symlink it to here.
if [ ! -L "$FISH" ]; then
    info "Fish config not symlinked, symlinking..."
    ln -s "$BASE_PATH/fish/fish" "$FISH"
fi
