#!/usr/bin/env zsh

FISH="$HOME/.config/fish"

# If it's not a symlink, symlink it to here.
if [ ! -h "$FISH" ]; then
    info "Sublime User package not synced, symlinking..."
    ln -s "$BASE_PATH/fish/fish" "$FISH"
fi
