#!/usr/bin/env zsh

FISH="$HOME/.config/fish"

# If it's not a symlink, symlink it to here.
if [ -z "$FISH" ]; then
    info "Fish config not symlinked, symlinking..."
    ln -s "$HOME/.dotfiles/fish/fish/" "$FISH"
fi
